name: photo_opener
description: "This package can open your photos just like in Telegram. From assets or network."
version: 0.1.9
homepage: https://github.com/ObidjonJoraboyev/photo_opener

environment:
  sdk: ^3.5.4
  flutter: ">=1.20.0"
example:
  directory: example
dependencies:
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  flutter_lints: ^5.0.0

  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.photo_opener
        pluginClass: PhotoOpener
      ios:
        pluginClass: PhotoOpener